#+Title: Web Radio Prototype
#+Author: Jared Smith, Sam Beveridge

* About

[[https://jared-n-sams-fun-playhouses.github.io/web-radio-proto][Click here for demo]]

[[http://jared-n-sams-fun-playhouses.github.io/web-radio-proto/][click here for gh-pages link]]

The idea is to have a way to provide an easy means of creating a radio show, using what web technologies that are available.

This may move to a more desktop oriented package if we find the web browser not suitable enough. If so, probably use Qt with C++, java with javafx, nodejs, etc.

This might work in mobile space too, but won't pursue until the backend logistics are working.

* Motor Templates

This is part of the [[https://github.com/mozilla/mortar/][mortar]]
template collection for building
[[https://developer.mozilla.org/Apps][Open Web Apps]].

** Project Walkthrough

The =manifest.webapp= file contains metadata about the app, such as its
name, description, icon and required permissions for running under
Firefox OS.

Moving over to =index.html=, this is the starting point for the app when
it's launched, and also where the layout is defined and the JavaScript
files with the functionality and logic are loaded.

The appearance is defined in =css/app.css=. There are just some very
basic rules.

We define the app's behaviour in =js/app.js=. Right now we're just
basically displaying a "Hello world" message.

Finally we are also including =js/libs/l10n.js=, which contains
[[https://developer.mozilla.org/en-US/docs/Web/API/L10n_API][L10n]], a
library for translating the strings in the app. Using this library,
users can run the app in their own language, as long as you provide the
translations for those languages. We're currently including a
translation to Spanish as an example, but feel free to contribute with
more translations in =data/locales.ini=, looking at =data/es.properties=
and =data/en-US.properties= to see the syntax in action. The way it
works, it will automatically translate the HTML elements that contain a
=data-l10n-id= attribute with the translation identifier.

For any dynamically shown content, you need to use the
=navigator.webL10n.get= function, but since that is slightly tedious to
write each time, we're aliasing it to just =translate=:

#+BEGIN_EXAMPLE
    var translate = navigator.mozL10n.get;
#+END_EXAMPLE

** Getting help

If you find something that doesn't quite work as you'd expect, we'd
appreciate if you
[[https://github.com/mozilla/mortar-privileged-empty-app/issues][filed a
bug]]!

We need your help in order to help you. Therefore:

1. Tell us which version of the template are you using. Where did you
   get the code from?

-  Specify the environment where the bug occurs i.e. which version of
   the Simulator or Firefox OS device. An example would be
   =1.2 simulator= or =Boot2Gecko 1.4.0.0=.
-  Describe the problem in detail. What were you doing? What happened?
   What did you expect to happen?
-  Probably also provide a test case so we can see what is happening and
   try to reproduce the error.

Ultimately it all boils down to the fact
